spring: 
  application:
    name: proudct-enquiry-service
 
server:
  port: 8700
  
  #Following config is not required if we use eureka server
#product-stock-service:
#  ribbon:
  #  listOfServers: http://localhost:8800,http://localhost:8801