spring:
  application: 
    name: product-stock-service

server: 
  port: 8800
  
  
  
 #Following configuration is not required if Eureka server is running on default port (8761)
#eureka:
 # client:
  #  serviceUrl:
 #     defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}